services:
  db:
    container_name: taskleaf_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    container_name: taskleaf_web
    build: .
    volumes:
      - .:/taskleaf
      - bundle:/usr/local/bundle
      - node_modules:/taskleaf/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    stdin_open: true
    tty: true
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
volumes:
  bundle:
  node_modules:
