services:
  db:
    container_name: taskleaf_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    container_name: taskleaf_web
    build: .
    volumes:
      - .:/taskleaf
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
    stdin_open: true
    tty: true